-- public.customer_vehicles definition

-- Drop table

-- DROP TABLE public.customer_vehicles;

CREATE TABLE public.customer_vehicles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	customer_id int4 NOT NULL,
	vehicle_id int4 NOT NULL,
	is_primary bool NOT NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT "PK_customer_vehicles" PRIMARY KEY (id)
);
CREATE INDEX "IX_customer_vehicles_customer_id" ON public.customer_vehicles USING btree (customer_id);
CREATE INDEX "IX_customer_vehicles_vehicle_id" ON public.customer_vehicles USING btree (vehicle_id);


-- public.customer_vehicles foreign keys

ALTER TABLE public.customer_vehicles ADD CONSTRAINT "FK_customer_vehicles_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;
ALTER TABLE public.customer_vehicles ADD CONSTRAINT "FK_customer_vehicles_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE CASCADE;


-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	full_name varchar(200) NOT NULL,
	email varchar(200) NOT NULL,
	phone varchar(20) NULL,
	identification_number varchar(50) NULL,
	is_active bool NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_customers" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_customers_email" ON public.customers USING btree (email);


-- public.monthly_subscriptions definition

-- Drop table

-- DROP TABLE public.monthly_subscriptions;

CREATE TABLE public.monthly_subscriptions (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	customer_id int4 NOT NULL,
	subscription_code varchar(50) NOT NULL,
	start_date timestamptz NOT NULL,
	end_date timestamptz NOT NULL,
	is_active bool NOT NULL,
	amount_paid numeric(10, 2) NOT NULL,
	max_vehicles int4 NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_monthly_subscriptions" PRIMARY KEY (id)
);
CREATE INDEX "IX_monthly_subscriptions_customer_id" ON public.monthly_subscriptions USING btree (customer_id);
CREATE UNIQUE INDEX "IX_monthly_subscriptions_subscription_code" ON public.monthly_subscriptions USING btree (subscription_code);


-- public.monthly_subscriptions foreign keys

ALTER TABLE public.monthly_subscriptions ADD CONSTRAINT "FK_monthly_subscriptions_customers_customer_id" FOREIGN KEY (customer_id) REFERENCES public.customers(id) ON DELETE CASCADE;

-- public.operators definition

-- Drop table

-- DROP TABLE public.operators;

CREATE TABLE public.operators (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	full_name varchar(200) NOT NULL,
	email varchar(200) NULL,
	username varchar(100) NOT NULL,
	password_hash text NOT NULL,
	is_active bool NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_operators" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_operators_username" ON public.operators USING btree (username);


-- public.payments definition

-- Drop table

-- DROP TABLE public.payments;

CREATE TABLE public.payments (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	ticket_id int4 NOT NULL,
	operator_id int4 NOT NULL,
	amount numeric(10, 2) NOT NULL,
	payment_method text NOT NULL,
	payment_datetime timestamptz NOT NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT "PK_payments" PRIMARY KEY (id)
);
CREATE INDEX "IX_payments_operator_id" ON public.payments USING btree (operator_id);
CREATE INDEX "IX_payments_ticket_id" ON public.payments USING btree (ticket_id);


-- public.payments foreign keys

ALTER TABLE public.payments ADD CONSTRAINT "FK_payments_operators_operator_id" FOREIGN KEY (operator_id) REFERENCES public.operators(id) ON DELETE RESTRICT;
ALTER TABLE public.payments ADD CONSTRAINT "FK_payments_tickets_ticket_id" FOREIGN KEY (ticket_id) REFERENCES public.tickets(id) ON DELETE CASCADE;


-- public.rates definition

-- Drop table

-- DROP TABLE public.rates;

CREATE TABLE public.rates (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	rate_name varchar(100) NOT NULL,
	hourly_rate numeric(10, 2) NOT NULL,
	fraction_rate numeric(10, 2) NOT NULL,
	daily_cap numeric(10, 2) NULL,
	grace_period_minutes int4 NOT NULL,
	is_active bool NOT NULL,
	effective_from timestamptz NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_rates" PRIMARY KEY (id)
);

-- public.shifts definition

-- Drop table

-- DROP TABLE public.shifts;

CREATE TABLE public.shifts (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	operator_id int4 NOT NULL,
	shift_start timestamptz NOT NULL,
	shift_end timestamptz NULL,
	initial_cash numeric(10, 2) NOT NULL,
	final_cash numeric(10, 2) NULL,
	status text NOT NULL,
	created_at timestamptz NOT NULL,
	CONSTRAINT "PK_shifts" PRIMARY KEY (id)
);
CREATE INDEX "IX_shifts_operator_id" ON public.shifts USING btree (operator_id);


-- public.shifts foreign keys

ALTER TABLE public.shifts ADD CONSTRAINT "FK_shifts_operators_operator_id" FOREIGN KEY (operator_id) REFERENCES public.operators(id) ON DELETE CASCADE;

-- public.subscription_vehicles definition

-- Drop table

-- DROP TABLE public.subscription_vehicles;

CREATE TABLE public.subscription_vehicles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	subscription_id int4 NOT NULL,
	vehicle_id int4 NOT NULL,
	added_at timestamptz NOT NULL,
	CONSTRAINT "PK_subscription_vehicles" PRIMARY KEY (id)
);
CREATE INDEX "IX_subscription_vehicles_subscription_id" ON public.subscription_vehicles USING btree (subscription_id);
CREATE INDEX "IX_subscription_vehicles_vehicle_id" ON public.subscription_vehicles USING btree (vehicle_id);


-- public.subscription_vehicles foreign keys

ALTER TABLE public.subscription_vehicles ADD CONSTRAINT "FK_subscription_vehicles_monthly_subscriptions_subscription_id" FOREIGN KEY (subscription_id) REFERENCES public.monthly_subscriptions(id) ON DELETE CASCADE;
ALTER TABLE public.subscription_vehicles ADD CONSTRAINT "FK_subscription_vehicles_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE RESTRICT;

-- public.tickets definition

-- Drop table

-- DROP TABLE public.tickets;

CREATE TABLE public.tickets (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	folio varchar(50) NOT NULL,
	vehicle_id int4 NOT NULL,
	operator_id int4 NOT NULL,
	subscription_id int4 NULL,
	entry_datetime timestamptz NOT NULL,
	exit_datetime timestamptz NULL,
	ticket_type text NOT NULL,
	status text NOT NULL,
	parking_duration_minutes int4 NULL,
	qr_code_data varchar(500) NOT NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_tickets" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_tickets_folio" ON public.tickets USING btree (folio);
CREATE INDEX "IX_tickets_operator_id" ON public.tickets USING btree (operator_id);
CREATE INDEX "IX_tickets_subscription_id" ON public.tickets USING btree (subscription_id);
CREATE INDEX "IX_tickets_vehicle_id" ON public.tickets USING btree (vehicle_id);


-- public.tickets foreign keys

ALTER TABLE public.tickets ADD CONSTRAINT "FK_tickets_monthly_subscriptions_subscription_id" FOREIGN KEY (subscription_id) REFERENCES public.monthly_subscriptions(id) ON DELETE SET NULL;
ALTER TABLE public.tickets ADD CONSTRAINT "FK_tickets_operators_operator_id" FOREIGN KEY (operator_id) REFERENCES public.operators(id) ON DELETE RESTRICT;
ALTER TABLE public.tickets ADD CONSTRAINT "FK_tickets_vehicles_vehicle_id" FOREIGN KEY (vehicle_id) REFERENCES public.vehicles(id) ON DELETE RESTRICT;

-- public.vehicles definition

-- Drop table

-- DROP TABLE public.vehicles;

CREATE TABLE public.vehicles (
	id int4 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START 1 CACHE 1 NO CYCLE) NOT NULL,
	license_plate varchar(20) NOT NULL,
	vehicle_type text NOT NULL,
	brand varchar(100) NULL,
	model varchar(100) NULL,
	color varchar(50) NULL,
	created_at timestamptz NOT NULL,
	updated_at timestamptz NOT NULL,
	CONSTRAINT "PK_vehicles" PRIMARY KEY (id)
);
CREATE UNIQUE INDEX "IX_vehicles_license_plate" ON public.vehicles USING btree (license_plate);